### ISSUE TITLE
Branch creation

### ISSUE THREAD

**Issue by NourGritli** [NourGritli/Bon-Voyage#4]
Hey guys, 
@omodev @matinmlk @xenoash @zohrehhanza @farzamhm @mazinabass 
Every one of us has to create a branch and commit his suggestions/work to his own branch. The files commited to the master branche are FINAL VERSIONS that most of us agreed on. Any changes in the master will be made upon a pull request and after being approved by the majority of the team members.

Thank you

**Comment by omodev** [comment]
Thank you Nour.
 And guys if you need help with how to create your own branch and make pull requests you can just ask or search on google !

**Comment by xenoash** [comment]
I do agree with you, Nour. 

Github is the right place to come to an agreement on the final version of any deliverable we are working on as it also gives us **essential experience**. 

P.S. I also recommend activating the notifications of the repository by clicking on the watch button on the top right of the repo page to receive email notifications on each activity.

Thanks!
